### ISSUE TITLE
Smooth transitions

### ISSUE THREAD

**Issue by Keith94** [Ashyni/mpv-scripts#15]
I'm not sure if possible but would be nice if the transitions were less abrupt when cropping the black bars. Especially for movies like The Dark Knight that have a dynamic aspect ratio, having a smooth cropping operation would be easier on the eyes i.e. when film goes 16:9 => 21:9 the video enlarges gradually

**Comment by Ashyni** [comment]
Hello, I didn't include you in https://github.com/Ashyni/mpv-scripts/commit/7828cc71dad30aa374d0da7d80b1aea79b923080 but i think it's the best i can do for now.
read_ahead_mode `1 or 2` provide a better timing, so the change feel less abrupt.

**Comment by Keith94** [comment]
Thanks! Can't test it now, but I will trust that it's fixed/improved.
