### ISSUE TITLE
dynamic-crop.lua script causes OSD to bug out in fullscreen

### ISSUE THREAD

**Issue by geextahslex** [Ashyni/mpv-scripts#20]
**Setup (please complete the following information):**
 - OS: Windows 7 Build 7601 Service Pack 1
 - Player: mpv 
 - Player Version: v0.36.0
 - Video Quality: 1080pH.264 /2160p HDR H265 or any song, doesn't matter

**Additional context**
MPV config:
script="C:\Program Files\MPV\scr\dynamic-crop.lua"
hwdec=no
vo=gpu-next

### Log file
[output.txt](https://github.com/Ashyni/mpv-scripts/files/12311575/output.txt)

**Describe the bug**
When you go fullscreen, the OSD bugs out, pulsates/flickers. OSD doesn't disappear after time, it displays all the time.

**Expected behavior**
After fullscreen, OSD acts as usual, don't bug out, and disappear after 2 seconds.

**Screenshots**
![dfdf](https://github.com/Ashyni/mpv-scripts/assets/139760266/1ccf5430-b5eb-4256-94a7-bc2c629b8162)

**Comment by Ashyni** [comment]
Hello, can't reproduce and never had this issue.

The logs are incomplete, doesn't show dynamic crop loading, etc. Example:
```
[   0.012][d][dynamic_crop] Loading lua script C:\Users\xxxxx\mpv-scripts\dynamic-crop.lua...
[   0.015][d][dynamic_crop] reading options for dynamic_crop
...
[   0.266][i][dynamic_crop] File loaded.
```

But i see you're using DEL shortcut, which is used to toggle OSC visibility between Never, Auto and Always.
May be it's your issue.

**Comment by geextahslex** [comment]
I don't know, I just put in cmd "mpv --log-file=output.txt" and thats it.
What do you mean by "DEL shortcut"? Do you have any suggestions what I can try out to fix this?

I am a noob, I use mvp since 4 days or so.

**Comment by Ashyni** [comment]
> I don't know, I just put in cmd "mpv --log-file=output.txt" and thats it.

add in `mpv.conf` instead, to get the logs in any case.
`log-file=output.txt`

> What do you mean by "DEL shortcut"? Do you have any suggestions what I can try out to fix this?

The touch DEL from your keyboard, make sure the settings is never or auto.

> I am a noob, I use mpv since 4 days or so.

It's ok, but i don't think the issue is related to the script.

**Comment by Ashyni** [comment]
Win 7 / driver, anything.
