### ISSUE TITLE
fix_windowed_behavior=0 not working on first playback

### ISSUE THREAD

**Issue by signin404** [Ashyni/mpv-scripts#23]
**Setup (please complete the following information):**
 - OS: Windows
 - Player: shinchiro/mpv-winbuild-cmake
 - Player Version: v0.37.0-754-g58eae25f
 - Video Title:
 - Video Quality:

**Additional context**
window-maximized = yes
auto-window-resize = no
fix_windowed_behavior = 0

**Describe the bug**
Window is resized to video size after first playback is stopped or files are switched

**Expected behavior**
Window remains maximized after first playback is stopped or after switching files

**Screenshots**

**Comment by Ashyni** [comment]
Hello, you should be able to use the default `fix_windowed_behavior = 1` (fix-no-resize) and can also remove `auto-window-resize = no` from your mpv.conf if you want.
Let me know if the issue isn't fixed.
It's not an issue on older mpv build (not sure when it changes).
