### ISSUE TITLE
Cropping stops working when someone seeks in syncplay.

### ISSUE THREAD

**Issue by Marctraider** [Ashyni/mpv-scripts#7]
As soon as a friend in the party does something that messes up the video, like seeking or pause, the script stops working and I have to leave the syncplay party and rejoin.

**Comment by Ashyni** [comment]
Hello, I'll investigate in a few days, already notice some rare case when this happened.

**Comment by Ashyni** [comment]
The commit closed the issue automatically, let me know if it's not fix.

**Comment by Marctraider** [comment]
Thanks, I'll let you know if this reoccurs or whether its fixed!

**Comment by Marctraider** [comment]
This appears to be fixed.
