### ISSUE TITLE
Movie lagging for minutes, every time dark scene appears.

### ISSUE THREAD

**Issue by Marctraider** [Ashyni/mpv-scripts#9]
Movie lagging for minutes, every time dark scene appears.

I'm not sure it this can be fixed without using only a one-shot approach.

Lacking any documentation, how can you actually set the script to use a one-shot approach? Like only scan the first few minutes of a movie and settle after that?

Thanks!

**Comment by memehammad** [comment]
I'm having the same issue, how did you fix this?

**Comment by Marctraider** [comment]
I didn't, other than set the script to 'one-shot'.

Only problem here is that jellyfin lags as long as dark scenes appear until the script has 'settled' on the desired cropping. But after that, everything works in order and the script remains dormant.

**Comment by memehammad** [comment]
Alright thank you for your help, I'm trying to watch a movie that keeps switching between 21:9 and 1,43:1 so I guess I'll just use Edge and ultrawidify for that one.

**Comment by Ashyni** [comment]
Hello, assuming the client is Jellyfin media player, from testing you need to tick UseOpenGL with the script to have good performance.
You can also update the mpv.dll used by JMP with this one from mpv-dev-xxxx.zip at https://sourceforge.net/projects/mpv-player-windows/files/libmpv/, rename the current `mpv.dll` to `mpv_bak.dll` and copy/rename the new `mpv-2.dll` to `mpv.dll`.
Also, an update to QT6.2 could probably help JMP performance, but no idea if it's planned.
